### ISSUE TITLE
Benchmark results

### ISSUE THREAD

**Issue by BakerBunker** [lucadellalib/audiocodecs#1]
Thank you for this wonderful repo, is there any result in the /benchmark section?

**Comment by BakerBunker** [comment]
Is it the same as this paper? https://arxiv.org/pdf/2406.14294

**Comment by lucadellalib** [comment]
Thank you! In the `benchmarks` section you can find example implementations for a few tasks and simple models from which you can draw inspiration to implement your own tasks.
If you’re looking for results, you can find the official DASB benchmarks here: https://github.com/speechbrain/benchmarks/tree/main/benchmarks/DASB

**Comment by BakerBunker** [comment]
Thank you for your response!
